### ISSUE TITLE
bundle.js is too large to download, not minified

### ISSUE THREAD

**Issue by cyio** [bigearth/bitbox.earth#11]
https://www.bitbox.earth/bundle.js

![image](https://user-images.githubusercontent.com/3146103/39987568-b9e673c2-5797-11e8-8ac3-12ef4dd4c3e6.png)

**Comment by cgcardona** [comment]
Thanks for pointing this out. I'll get it minified.

**Comment by cgcardona** [comment]
bundle.js is now minified. Thanks for bringing this to my attention.
